In [1]:
! pip install numpy

In [2]:
l = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9, 10]
]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9, 10]]

In [3]:
import numpy

In [4]:
l = [1, 2, 3, 4, 5]
# converting list into numpy array
arr = numpy.array(l)
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.ndim  # number of dimensions of the array

1

In [8]:
arr2 = numpy.array(10)
print(arr2)
print(type(arr2))
print(arr2.ndim)  # should be 0, as it is a scalar

10
<class 'numpy.ndarray'>
0


In [10]:
l = [
    [1, 2, 3],
    [4, 5, 6]
]
arr3 = numpy.array(l)
print(arr3)
print(type(arr3))
print(arr3.ndim) 

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2


# 0-d array

In [11]:
a = 2
arr = numpy.array(a)
print(arr)
print(type(arr))
print(arr.ndim)  # should be 0, as it is a scalar
print(arr.shape)  # should be empty tuple, as it is a scalar

2
<class 'numpy.ndarray'>
0
()


### 1-D Array

In [20]:
l = [1, 2, 3, 4]
arr1 = numpy.array(l)
print(arr1)
print(type(arr1))
print(arr1.ndim)  # should be 1, as it is a 1
print(arr1.shape)  # should be (4,), as it is a 1-D array with 4 elements

[1 2 3 4]
<class 'numpy.ndarray'>
1
(4,)


In [17]:
arr1[2]

np.int32(3)

In [ ]:
l= [1, 2, 3, 4]
arr1 = numpy.array(l, dtype=numpy.int32)
arr1[2]

In [21]:
l= [1, 2, 3, 4]
arr1 = numpy.array(l, dtype=numpy.float32)
arr1[2]

np.float32(3.0)

In [22]:
arr1

array([1., 2., 3., 4.], dtype=float32)

In [34]:
arr1.dtype

dtype('float32')

# 2-D Array

In [23]:
l = [
    [1, 2, 3],
    [4, 5, 6]
]
arr2 = numpy.array(l)
print(arr2)
print(type(arr2))
print(arr2.ndim)  # should be 2, as it is a 2-D array
print(arr2.shape)  # should be (2, 3), as it is a

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2
(2, 3)


In [24]:
arr2[1][2]

np.int64(6)

In [25]:
arr2[1, 2]

np.int64(6)

# 3-D Array

In [29]:
l = [
    [
      [1, 2],
      [3, 4]
    ],
    [
      [5, 6],
      [7, 8]
    ]
]
arr3 = numpy.array(l)
print(arr3) 
print(type(arr3))
print(arr3.ndim)  # should be 3, as it is a 3
print(arr3.shape)  # should be (2, 2, 2), as it is a 3-D array with shape 2x2x2

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>
3
(2, 2, 2)


In [32]:
arr3[1,0,1]

np.int64(6)

In [35]:
arr3.dtype

dtype('int64')

In [37]:
arr = numpy.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [38]:
arr.shape

(20,)

In [39]:
arr.reshape((1,20))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [40]:
arr.reshape((4, 5))  # reshaping the array to 4 rows and 5 columns

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [41]:
arr.reshape((2,2,5))

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])